### ISSUE TITLE
[Question] How to access global variables (window.x) in Vue 3 templates?

### ISSUE THREAD

**Issue by mariusa** [vuejs/vue-next-webpack-preview#15]
In Vue 2, one could do this

main.js
```
   Vue.prototype.window = window
    window.org = 'Santa'
```

Without anything added to vue.config.js, this worked in any Vue template:
```
    window.org {{ window.org }}
```

With Vue 3, this errors with 
```TypeError: Cannot read property 'org' of undefined```

How to access global variables (window.x) in Vue 3 templates?

**Comment by yyx990803** [comment]
`app.config.globalProperties.window = window`

**Comment by mariusa** [comment]
Thank you, Evan! May I followup, please?

main.js
```
let app = createApp(App)
app.config.globalProperties.window = window //reactive(window) doesn't make org2 work
window.org1 = 'Santa' //this works, because it's before mount?
app.mount('#app')
window.org2 = 'Santa' //not rendered in template

//why isn't this rendered in template after being set with reactive() ? usecase: data loaded later, after app.mount()
app.config.globalProperties.org3 = reactive({
    settings: {
        foo: 'Santa',
    },
})

window.org1 = 'Rudolf' //not updated in template, even if using reactive() initially
```

App.vue template
```
    <p>window.org1 {{ window.org1 }}</p>
    <p>window.org2 {{ window.org2 }}</p>

    <p>global org3 {{ org3 }}</p>
    <p v-if="org3">org3.settings.foo {{ org3.settings.foo }}</p>
```

result
```
window.org1 Santa

window.org2

global org3
```

How can we make org3, maybe also window.org2, work?

**Comment by yyx990803** [comment]
It's a really, really bad idea to use `window` as a reactive object. Why not just use a custom `reactive({})` instead?

**Comment by mariusa** [comment]
Thanks. This is what I'm trying with ```org3```. How to use the 'custom' that you mention?

So:
```
app.config.globalProperties.org3 = reactive({})
app.mount('#app')
app.config.globalProperties.org3 = reactive({
    settings: {
        foo: 'Santa',
    },
})
```

```
    <p>global org3 {{ org3 }}</p>
    <p v-if="org3.settings">org3.settings.foo {{ org3.settings.foo }}</p>
```

Does it lose reactivity due to direct assign? What would be the proper way to update ```org3``` with a deep object?
Vue 2 guide says ```Object.assign()``` doesn't work for new properties.

**Comment by yyx990803** [comment]
`globalProperties` itself is non-reactive. You can only trigger changes by mutating `org3`. Vue 3 can detect property additions and deletions (as long as you don't plan to support IE11)

**Comment by mariusa** [comment]
> Vue 3 can detect property additions and deletions (as long as you don't plan to support IE11)

Excellent!

> You can only trigger changes by mutating org3.

This would be the best way? It works :)
```
let app = createApp(App)
app.config.globalProperties.org3 = reactive({})
app.mount('#app')

let org3_data = {
    settings: {
        foo: 'Santa',
    },
}
app.config.globalProperties.org3 = Object.assign(app.config.globalProperties.org3, org3_data)
```

Last question: how to access ```org3``` / ```globalProperties``` in various Vue views?

eg in App.vue
```
export default {
    setup() {
...
        console.log('setup')
        org3.settings.foo = 'from setup' //this works inside <template>, but not here 


    },
}
```

**Comment by yyx990803** [comment]
Just import it? But what you are doing really is more like a shared global store... it's better to just explicitly import the reactive object in components that need it (and return from `setup` to use in templates), instead of exposing it via `globalProperties`.

**Comment by ansarizafar** [comment]
> Just import it?

How can we import globalProperties in a component?

**Comment by waruyama** [comment]
@ansarizafar 

I don't think you have to import them, they should already be available. Here is how I make `$store` available to a component:

in `main.js`:
```
const app = createApp(App);
app.config.globalProperties.$store = store;
```

In a single file component this can be accessed through `this.$store`:

```
...
methods: {
  doSomething: function() {
    let foo = this.$store.state.foo;
    ...
  },
...
```

**Comment by orafal-dev** [comment]
@ansarizafar and how would you do that in `setup() {}` ?

**Comment by techieoriname** [comment]
> @ansarizafar and how would you do that in `setup() {}` ?

same question here

**Comment by martinszeltins** [comment]
> @ansarizafar and how would you do that in `setup() {}` ?

This might be considered an anti-pattern but you can do it like this. This works with the latest version 3.0.4

````
<script setup>
    import { getCurrentInstance } from 'vue'

    const app = getCurrentInstance()
    const $store = app.appContext.config.globalProperties.$store

    console.log($store)
</script>
````

**Comment by krry** [comment]
> This might be considered an anti-pattern but you can do it like this. This works with the latest version 3.0.4

I keep coming back to this. Why is this potentially an anti-pattern? Often in the setup of a component I think I want to bring data in from a central store.  Or does this fit in a later stage of the lifecycle?
