### ISSUE TITLE
"development" build fails to load

### ISSUE THREAD

**Issue by jayars** [vuejs/vue-next-webpack-preview#6]
Not sure if this is a bug or intended behaviour:

When I run `webpack` without `--env.prod`, and host it using a simple http server (ie, `lite-server`), the page fails to load.

```
Paused on exception
TypeError: Cannot read property 'instances' of undefined.
```

![image](https://user-images.githubusercontent.com/28939507/72160004-8b49d880-33f8-11ea-9a90-ac224829f3cf.png)

**Comment by yyx990803** [comment]
Fixed in `vue-loader@16.0.0-alpha.2`
