### ISSUE TITLE
[Question] How to enable runtime template compilation

### ISSUE THREAD

**Issue by RobinHavre** [vuejs/vue-next-webpack-preview#8]
```
Vue warn]: Component provides template but the build of Vue you are running does not support runtime template compilation. Either use the full build or pre-compile the template using Vue CLI.
```

What is the best way to enable runtime template compilation? So that components can be registered at runtime using ``app.component('name',{})``

I have tried editing ``webpack.config.js`` , changing the alias to ``'vue': 'vue/dist/vue.esm.js'``, but to no effect.

**Comment by yyx990803** [comment]
You don't need runtime compilation to register global components:

``` js
import Foo from './Foo.vue'

app.component('name', Foo)
```

The only reason you want to have runtime template compilation is when you have no way but to inline your template a JavaScript strings, or you need to write your templates directly in the DOM. Enabling runtime compilation has performance costs.

**Comment by RobinHavre** [comment]
My question was a bit unclear, in our case it is in fact the runtime compilation we are after.

**Comment by yyx990803** [comment]
In that case you need to configure your bundler alias so that `vue` points to the dist file that includes the runtime compiler (`node_modules/vue/dist/vue.esm-bundler.js`)

**Comment by RobinHavre** [comment]
The alias was changed in webpack.config.js, that's why I'm curious if this might be a bug. 

The webpack.config.js looks like this, and the same ``does not support runtime template compilation``-error is still appearing:
```javascript
const path = require('path')
const { VueLoaderPlugin } = require('vue-loader')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')

module.exports = (env = {}) => ({
  mode: env.prod ? 'production' : 'development',
  devtool: env.prod ? 'source-map' : 'cheap-module-eval-source-map',
  entry: path.resolve(__dirname, './src/main.js'),
  output: {
    path: path.resolve(__dirname, './dist'),
    publicPath: '/dist/'
  },
  resolve: {
    alias: {
      'vue': 'vue/dist/vue.esm-bundler.js'
    }
  },
  ...
```
